obsproject/obs-websocket

- PROTOCOL.md
- WSEvents.cpp
- WSEvents.h
Was finally able to get this project to run locally. My issue was that it wasn't copying the QT5WebSocket and QT5Network dlls to the proper directory at build time - it would include them in the run directory, but in the wrong location. 
If I manually relocate them I can get the solution to run, but it's kind of hacky and I need to figure out what's different between your environment and mine.
Also had a slew of issues with the mbed dependencies and wound up having to add to my local CMakeLists to get those picked up properly.
Anyways. Small commit, two additional events + brief API docs.
> [Protocol] Add OnTransitionChange/OnTransitionListChange (Fixes #19)

- data/locale/de-DE.ini
Add german translation for menu entry and settings dialog.
> Add german translation

- PROTOCOL.md
- WSRequestHandler.cpp
Adds the ability to specify a scene when calling SetSourceRender.
> Toggle source on specified scene

- PROTOCOL.md
- Utils.cpp
- Utils.h
- WSRequestHandler.cpp
Same as #45 but for SceneItemPosition and SceneItemTransform.  Moved code I found I was repeating to Utils.
> Add scene name to SetSceneItemPosition and SetSceneItemTransform

- data/locale/zh-CN.ini
- data/locale/zh-TW.ini
`zh-CN.ini` for Simplified Chinese and `zh-TW.ini` for Traditional Chinese. Language code are same as [OBS Studio](https://github.com/jp9000/obs-studio/tree/master/UI/data/locale).
> Add chinese translation

- data/locale/pl-PL.ini
> Polish locale

- data/locale/nl-NL.ini
Small addition of dutch localization
> Dutch Locale

- WSEvents.cpp
Go figure, I typo'd the very first event.
> Update api doc for SwitchScenes

- WSEvents.cpp
- WSRequestHandler.cpp
- docs/generated/comments.json
- docs/generated/protocol.md
- docs/protocol.hbs
Just started on this, but I'm boarding a plane in 5 minutes. I'll finish up the rest of the requests later and clean up the generated doc a bit to account for unreleased stuff more gracefully.
> docs: Add @since

- WSRequestHandler.cpp
- docs/protocol.hbs
> docs: Add deprecated attribute

- Utils.cpp
- Utils.h
- WSRequestHandler.cpp
- WSRequestHandler.h
See line specific questions below @Palakis @haganbmj
> [Safe For Merge] Unified Setter and Getter for scene specific source properties

- WSRequestHandler.cpp
> docs: correct GetSceneItemProperties name

- CI/install-build-obs.cmd
- CI/install-setup-qt.cmd
- appveyor.yml
This PR will (hopefully) fix CI builds on Windows and Linux.  This addresses items 1, 2, and partly 3 from #143.  I figured I'd work on items 3 and (optionally) 4 if this PR works, and if those items are wanted.  This will need to be merged before the CI services will use the updated config files.
Commits are squashable if needed/desired.  Feedback and reviews welcome.
> Fix CI builds on Windows and Linux

- CI/install-build-obs.cmd
We should also build OBS with Visual Studio 2017.
I'm an idiot and forgot to update the OBS build script in PR #202.
I also have a few more tweaks for CI/CMake that I plan to submit to you.  Let me know if you'd like those as separate PRs, or as a single PR with multiple commits, or some other way.
> CI(Windows): Build OBS with Visual Studio 2017

- src/WSRequestHandler_Sources.cpp
Meant to include this in #219 but pushed to the wrong brach :upside_down_face:.
> docs: Fix typo

- CMakeLists.txt
- src/WSEvents.cpp
- src/WSEvents.h
Waiting for https://github.com/obsproject/obs-studio/commit/dd7742ffc0abca695dc569d3cb40c1d14960e8bb to get merged and released.
> [not ready] events: fix triggering of PreviewSceneChanged

- src/WSRequestHandler.cpp
- src/WSRequestHandler.h
- src/WSRequestHandler_Sources.cpp
- GetSourceFilters
- AddFilterToSource
- RemoveFilterFromSource
- SetSourceFilterSettings
- ReorderSourceFilter
- MoveSourceFilter
> Request types for filter management

- src/WSEvents.cpp
- src/WSRequestHandler_Scenes.cpp
- src/WSRequestHandler_Sources.cpp
- src/WSRequestHandler_Streaming.cpp
Fixed several typos throughout the project on the master branch.
> general: Fix several typos throughout

- docs/comments.js
- docs/generated/comments.json
- docs/generated/protocol.md
- docs/partials/typedefsHeader.md
- docs/protocol.hbs
- src/WSEvents.cpp
- src/WSRequestHandler_Profiles.cpp
- src/WSRequestHandler_SceneCollections.cpp
- src/WSRequestHandler_Scenes.cpp
- src/WSRequestHandler_Sources.cpp
- src/WSRequestHandler_StudioMode.cpp
- src/WSRequestHandler_Transitions.cpp
**Might not be ready to merge yet, please review carefully!**
This is part of the ongoing work in https://github.com/haganbmj/obs-websocket-js/pull/126
> docs: improve consistency of array typings; introduce typedefs category

- src/WSRequestHandler_SceneItems.cpp
- src/WSRequestHandler_Sources.cpp
And minor refactoring here and there.
> sources: get rid of unnecessary `scene-name` param on Source Request Types

- src/Utils.cpp
- src/WSRequestHandler_SceneItems.cpp
> GetSceneItemProperties: add width & height values

- src/WSEvents.cpp
- src/WSRequestHandler.cpp
- src/WSRequestHandler.h
- src/WSServer.cpp
> fix debug logging

- src/WSEvents.cpp
- src/WSEvents.h
> events(StreamStatus): new property "replay-buffer-active"

- src/WSEvents.cpp
- src/WSEvents.h
- src/WSServer.cpp
> server: implement "port already in use" message + fix crash with StreamStatus

- src/Utils.cpp
- src/WSRequestHandler_Recording.cpp
> SetRecordingFolder: fix docs + simplify helper function

- src/Utils.cpp
- src/WSEvents.cpp
> event(SourceOrderChanged): include scene items list

- src/WSEvents.cpp
- src/WSEvents.h
- src/WSRequestHandler.cpp
- src/WSRequestHandler.h
- src/WSRequestHandler_General.cpp
> Add more stats to StreamStatus and Heartbeat + add GetStats request type

- src/Utils.cpp
- src/WSEvents.cpp
- src/WSRequestHandler_SceneItems.cpp
- src/WSRequestHandler_Sources.cpp
> Provide scene item id in events data and request responses

- src/Utils.cpp
- src/Utils.h
- src/WSEvents.cpp
> event(TransitionBegin): set duration to 0 if it's a Cut transition

- src/Utils.cpp
- src/Utils.h
- src/WSRequestHandler_SceneItems.cpp
- src/WSRequestHandler_Scenes.cpp
- src/WSRequestHandler_StudioMode.cpp
- src/obs-websocket.cpp
> ReorderSceneItems: fix crash + refactor Utils

- src/WSEvents.cpp
> events(GetStats): fix recording path detection

- src/obs-websocket.cpp
> Start server after OBS finishes loading

- src/Utils.cpp
- src/Utils.h
- src/WSEvents.cpp
- src/WSEvents.h
- src/WSRequestHandler.cpp
- src/WSRequestHandler.h
- src/WSRequestHandler_Sources.cpp
> Get/set filter visibility (+ get single filter info)

- README.md
Since there are MacOS releases, it's probably worth mentioning it in the README
> Update README to include MacOS

- docs/generated/protocol.md
- src/WSRequestHandler_Sources.cpp
Corrected from String to Boolean
> Fix SetSourceFilterVisibility filterEnabled type

- src/WSRequestHandler_Streaming.cpp
> docs: replace stream service option use-auth with use_auth

- azure-pipelines.yml
- src/WSRequestHandler_Sources.cpp
> requests(SetSyncOffset): allow negative offsets

- src/WSRequestHandler_General.cpp
> request(GetVersion): add supported image export formats list

- CI/package-xenial.sh
- CMakeLists.txt
> Fix JPEG support in TakeSourceScreenshot on Windows

- src/WSRequestHandler_StudioMode.cpp
> Fix crash when calling EnableStudioMode/DisableStudioMode/ToggleStudioMode

- src/WSRequestHandler_Sources.cpp
> Allow Get/Set text gdiplus/ft2 properties functions to operate on v2 sources

- CMakeLists.txt
> cmake(msvc): disable FH4

- CI/package-ubuntu.sh
- CMakeLists.txt
> Ubuntu packaging fixes

- src/WSEvents.cpp
- src/WSRequestHandler_Scenes.cpp
- src/WSRequestHandler_Sources.cpp
- src/WSRequestHandler_Streaming.cpp
Fix a few build warnings on windows because im ocd
> General: Fix a few warnings

- src/WSRequestHandler.cpp
- src/WSRequestHandler.h
- src/WSRequestHandler_Scenes.cpp
Adds these requests:
- `SetSceneTransitionOverride`
- `RemoveSceneTransitionOverride`
- `GetSceneTransitionOverride`
Closes #512
> Requests: Add scene transition override requests

- src/WSRequestHandler.cpp
- src/WSRequestHandler.h
- src/WSRequestHandler_Scenes.cpp
First command of propositions from #522 
Discussion: should there also be bool `activate-immediately` in request, to activate new scene after creation?
Testing: UI updates properly.
edit by tt: Closes #522
> Create scene base functionality

- src/WSRequestHandler.cpp
- src/WSRequestHandler.h
- src/WSRequestHandler_Recording.cpp
- src/WSRequestHandler_ReplayBuffer.cpp
Adds `GetReplayBufferStatus` and `GetRecordingStatus`.
v5.0 Will remove the recording status functionality from `GetStreamingStatus`
Closes #548
> Requests: Add Replay Buffer and Recording Statuses

- src/WSEvents.cpp
- src/WSRequestHandler_MediaControl.cpp
Left in some old terms accidentally. This fixes it.
Am bad programmer (and high from post-surgery painkillers)
Tested OS(s): 
> Requests/Events: Use sourceKind instead of sourceTypeId

- CONTRIBUTING.md
- docs/partials/introduction.md
- docs/partials/requestsHeader.md
- src/WSEvents.cpp
- src/WSRequestHandler_General.cpp
- src/WSRequestHandler_MediaControl.cpp
- src/WSRequestHandler_Outputs.cpp
- src/WSRequestHandler_Profiles.cpp
- src/WSRequestHandler_Recording.cpp
- src/WSRequestHandler_ReplayBuffer.cpp
- src/WSRequestHandler_SceneCollections.cpp
- src/WSRequestHandler_SceneItems.cpp
- src/WSRequestHandler_Scenes.cpp
- src/WSRequestHandler_Sources.cpp
- src/WSRequestHandler_Streaming.cpp
- src/WSRequestHandler_StudioMode.cpp
Lots of changes, too many to list. All nonbreaking.
I noticed that some parts of the docs were inconsistent/lacking.
Decided to go through all of them and update them.
Fixes #561
> Docs: Various docs improvements

- src/WSEvents.cpp
Was noticed in Discord that this was missing from the docs
> Docs: Add `enabled` field to `SourceFiltersReordered`

- README.md
list multiple available web clients instead of only t2t2
because there's alternatives, that's a good thing and people should use which one they prefer.
yes
documentation changes
> docs: 📝 list multiple available web clients

- README.md
Included link to Dart API in the README.md file
I've made the API and would like to link it here.
I'm using this API in my APP https://github.com/renannoronha/obs_deck
Just one line of change on  the README.md file
> include Dart API

- .github/workflows/pr_push.yml
- .github/workflows/tag_release.yml
- CI/install-build-obs-macos.sh
- CI/prepare-obs-windows.cmd
- src/WSRequestHandler.cpp
- src/WSRequestHandler.h
- src/WSRequestHandler_Streaming.cpp
OBS has removed the `BUILD_CAPTIONS` flag from their repo. No reason to keep it
> CI: Remove BUILD_CAPTIONS flag

- README.md
They give us an A and I think that's pretty cool so might as well display it
Showing off
> README: Add codefactor badge

- README.md
I created a client library in Rust to remote control OBS with
obs-websocket. Adding my library to the list of available
language APIs.
Thought it might be nice to let other Rust devs know there is a client library.
Tested OS(s): 
> readme: Add Rust client library

- src/WSRequestHandler_Streaming.cpp
Fixes #622 
It wasn't included for some reason.
> Docs: Add recording-paused to documentation

- README.md
Give a short hint that the project can be installed with Homebrew on
MacOS as alternative to installing manually.
I added a Homebrew (Cask) Formula a while back that allows to simply install `obs-websocket` with `brew install obs-websocket` as alternative to manual installation. I thought it might be nice to mention that in the README.md.
Totally optional, but may be nice for people to know there is a convenient way to install the plugin.
Didn't really test, as this is just a change to the docs. But used a markdown previewer to make sure the output looks proper and tested the Homebrew Formula of course, as it wouldn't have been merged otherwise.
-   [x] I have read the [**contributing** …
> readme: Add Homebrew installation instructions

- src/ConnectionProperties.cpp
- src/ConnectionProperties.h
- src/Utils.h
- src/WSRequestHandler_Recording.cpp
- src/WSRequestHandler_ReplayBuffer.cpp
- src/WSRequestHandler_Sources.cpp
- src/WSServer.cpp
Replace 4-space code with tabs to conform with the way its supposed to be.
For consistency.
> Misc: Fix indentation of src files

- README.md
I created a client API Library for Java 11+. 
Shows other available Java API implementations. 
> readme: Added obs-java-client to the available API's

- CI/package-ubuntu.sh
Fixes tag detection for deb package building
CI was not properly detecting that it was building a tag, and so it was setting the deb package version incorrectly.
Tested OS(s): CI
> CI: Fix tag detection

- src/WSRequestHandler_MediaControl.cpp
Remove the Requirement for the boolean value, and implement a toggle function if no boolean parameter exists
A friend asked me to add this feature
Tested OS(s): 
Tested on windows
- Enhancement (modification to a current event/request which adds functionality) 
> Requests: Edit PlayPauseMedia 

- README.md
Adds Dart client library created by faithoflifedev
Client libraries should be given a platform
> README: Add Dart client library

- azure-pipelines.yml
I spotted this small typo looking at the changes made recently.
> Fix small pipeline typo

- CI/macos/obs-websocket.pkgproj
- CMakeLists.txt
- docs/partials/introduction.md
- installer/installer.iss
- src/WSEvents.cpp
- src/WSRequestHandler_General.cpp
- src/WSRequestHandler_Sources.cpp
- src/WSRequestHandler_VirtualCam.cpp
- src/obs-websocket.h
Do the according changes in order to release v4.9.1
n/a
> 4.9.1 Prep

- README.md
Add the Rust client library back to the list of libraries for v5.
Let Rust users know that they can already try out the client library with the v5 dev version.
Tested through several intergration tests, as usual. The rewrite for v5 is still a WIP so some tests are missing or incomplete.
-  [x] I have read the [**contributing** document](https://github.com/Palakis/obs-websocket/blob/4.x-current/CONTRIBUTING.md).
-  [ ] My code is not on the master branch.
> README: Add Rust obws to library list

- README.md
Docs update to include [obs-websocket-js](https://github.com/obs-websocket-community-projects/obs-websocket-js) as it supports v5 protocol
Library includes tests checking the sent websocket messages
---
Should this list maybe be alphabetical by language?
> README: Add obs-websocket-js to client libraries

- CMakeLists.txt
- lib/obs-websocket-api.h
- src/eventhandler/EventHandler_Inputs.cpp
- src/requesthandler/RequestHandler.cpp
- src/requesthandler/RequestHandler_Inputs.cpp
- src/websocketserver/WebSocketServer.cpp
Fix warnings and suppress the one that are in the deps folder.
Make also the project able to use Qt5 or Qt6 because obs-studio.
Make https://github.com/obsproject/obs-studio/pull/6468 pass the CI and also pass https://github.com/obsproject/obs-studio/pull/6759.
Tested OS(s): 
Test build with https://github.com/obsproject/obs-studio/pull/6468 and this PR on Windows, no issue with this PR.
Test build with also https://github.com/obsproject/obs-studio/pull/6759 on Linux and macOS, and no issue with it.
-  [x] All commit messages …
> Fix warnings to make the submodule PR work with CI and also add find_qt to CMake

- CMakeLists.txt
Make obs-websocket pass obs-studio CI
https://github.com/obsproject/obs-websocket/commit/420e600864fe8e2e6ff0208f61cd73640b81e372
Does this on CI:
```
D:\a\obs-studio\obs-studio\obs-studio\plugins\obs-websocket\deps\asio\asio\include\asio/detail/config.hpp(865,32): error C2177: constant too big [D:\a\obs-studio\obs-studio\obs-studio\build64\plugins\obs-websocket\obs-websocket.vcxproj]
D:\a\obs-studio\obs-studio\obs-studio\plugins\obs-websocket\deps\asio\asio\include\asio/detail/config.hpp(964,33): error C2177: constant too big [D:\a\obs-studio\obs-studio\obs-studio\build64\plugins\obs-websocket\obs-websocket.vcxproj]
D:\a\obs-studio\obs-studio\obs-studio\plugins\obs-websocket\deps\asio\asio\include\asio/detail/config.hpp(1153,34): error C2177: constant too big …
```
> Truly fix C4996 warning

- README.md
README update to show availability of Dart SDK for obs-websocket
Not applicable
Tested OS(s): 
- Not applicable
> README update to show availability of Dart SDK for obs-websocket

- README.md
Just realized that the link for `obws` was still pointing to the feature branch, that was already merged a while back.
Tested OS(s):
> docs: Update link to Rust client crate

- src/requesthandler/RequestHandler_Config.cpp
Fix the category of the `GetRecordDirectory` request.
The category was `rconfig` instead of `config` (probably a misspell), which caused it to be missing from the generated `protocol.md` documentation.
Tested OS(s):
-  [ ] I have included updates to all appropriate documentation.
> docs: Fix category of GetRecordDirectory`

- README.md
Add a reference to [OBS-web](https://github.com/Niek/obs-web) since it now support obs-websocket 5.0
Get people to know compatible clients.
Documentation change
-  [ ] The code has been tested. [not tested by me, but I guess the maintainer of the project did its test before releasing]
> README: Add OBS-web to client software

- README.md
Add Bitfocus Companion module to list of supported client software
Provide info about a supported client.
Documentation change
> README: Add Bitfocus Companion to client software

- docs/docs/partials/introduction.md
- docs/generated/protocol.md
It may be worth having the entire TOC up here, but this way, at least it's possible to jump to the other TOCs.
Add a couple more entries to the main TOC
Currently, the main TOC just links to the general info and message types, but not to the other major sections.
- The Python script had no complaints.
- Browsed the GitHub rendered version; it looks fine and the links go where I expect them to.
-  [x] I have included updates to all …
> docs: Add top-level headings to main TOC

- src/requesthandler/RequestHandler_General.cpp
- src/requesthandler/RequestHandler_Outputs.cpp
See #1042 
A regeneration of the protocol.json and protocol.md is to be expected
Fixes #1042 
Tested OS(s): 
Windows 11
> fix: Sleep request fields are exclusive so both optional fixes #1042

- README.md
Updated README to add Java library
Compatible v5 Java library first release
Tested OS(s): Windows 11
> doc: Update README to add Java library

- README.md
Added a link to the Macro Deck client software in the description
Macro Deck is a software to automate and control a pc and 3rd party services with the help of a smartphone or any other touchscreen device. OBS is one of the 3rd party services which can be controlled and automated with Macro Deck, that's why it should be listed in the description under "Client software".
- Documentation change (a change to documentation pages) 
-  [x] I have included updates to all appropriate …
> General: Added a link to Macro Deck in the description

- docs/docs/partials/introduction.md
Corrected 'compatability' to 'compatibility' in docs/docs/partials/introduction.md
N/A
Tested OS(s): N/A
- Documentation change (a change to documentation pages) 
> docs: Fix small typo in introduction.md

- .gitmodules
- CMakeLists.txt
Requires to work on obs-studio repo:
- https://github.com/obsproject/obs-deps/pull/155 (Asio 1.12.1)
- https://github.com/obsproject/obs-studio/pull/8194
Replace headers-only libraries submodules by prefix/system-wide install.
Reduce the number of submodules in obs-studio repo and provides those libraries in obs-deps.
Tested OS(s): 
obs-studio CI on my fork (https://github.com/tytan652/obs-studio/pull/10) with obs-websocket modified to be aware of obs-deps and custom-made finders for Asio and WebSocket++.
- Other Enhancement (anything not applicable to what is listed) 
-  [x] My …
> Replace headers-only libraries submodules by prefix/system-wide install

- .gitignore
Removes the entries for generated files from `.gitignore` file.
the commit 21886adb3 moves the destination of the generated files into the build directory so that it is unnecessary to hide the generated files by .gitignore.
By removing these entries, it's easier to find the unnecessary files by `git status` command.
Tested OS(s): Fedora 36
-  [ ] All commit messages are properly formatted and commits squashed where appropriate.
> base: Remove unnecessary entries in .gitignore

- README.md
Prevents Firefox from marking the links as a Potential Security Risk (not sure if it happens on other
It'll make more convenient to press on a link that doesn't have a warning.
Tested OS(s): 
I opened the link and it shows the warning. I tested it on Mac and Windows and both OS's have this issue and it fixes the issue.
-  [ ] All commit messages are properly formatted and commits squashed where appropriate.
-  [ ] My code is not on `master` or a `release/*` branch.
-  [ ] I have included updates to all appropriate documentation.
> README: Prevent Firefox from flagging Macro Deck as a security risk

- src/requesthandler/RequestHandler_Scenes.cpp
Fix the protocol document for SetSceneSceneTransitionOverride.
The API actually 'set' the transition override but the document says 'get'.
Tested OS(s): Linux
Just compiled and checked there is no error.
> base: Fix a comment for SetSceneSceneTransitionOverride

- README.md
Add Macrograph to Client Software in Readme
MacroGraph exposes OBS Websocket through a visual programming environment.
Its just a readme change. no testing required.
Documentation change (a change to documentation pages)
-  [X] I have read the [Contributing Guidelines](https://github.com/obsproject/obs-websocket/wiki/Contributing-Guidelines).
-  [X] All commit messages are properly formatted and commits squashed where appropriate.
-  [X] My code is not on `master` or a `release/*` branch.
-  [X] The code has been tested.
-  [X] I have included updates to all appropriate documentation.
> Readme: Add MacroGraph to client list

- README.md
I have updated [the Godot client library](https://github.com/you-win/obs-websocket-gd) to work on the latest version of Godot (4.0.2 at time of writing).
The current version of Godot mentioned in the README is very old (3.4.x).
Tested OS(s): Windows 10
Godot natively supports most major OSs and Linux distros. The client library does not use any OS-specific code. There is a simple demo scene that was used for testing requests.
-  [x] …
> README: Bump Godot client library to 4.0.x

- src/requesthandler/RequestHandler_Config.cpp
Uses the `obs_frontend_add_scene_collection` function for `CreateSceneCollection` instead of relying on the undocumented `AddSceneCollection`.
The "AddSceneCollection" method will likely be removed in a future (probably the next) version of OBS.
The frontend API function is currently just a wrapper around that method but that will be a problem for future me when I actually remove `AddSceneCollection`, it will continue to work.
Tested OS(s): 
macOS 13.2.1
Compiled successfully. Don't use websockets so can't test otherwise.
- …
> requesthandler: Use Frontend API for CreateSceneCollection
