obsproject/obs-websocket

- PROTOCOL.md
Thanks for picking up work on this for OBS Studio. Fiddled around with it this evening and wanted to update the Protocol doc with some of the expected fields.
I couldn't seem to find a way to trigger [RecordingStopping](https://github.com/Palakis/obs-websocket/blob/master/WSEvents.cpp#L154), so I left a "Not Yet Implemented" in the doc.
Also, I have no idea what preview-only means. I tried disabling my preview and projecting to another monitor and still couldn't get that flag to change.
> [API-docs] Update Event/Request Fields

- PROTOCOL.md
- WSRequestHandler.cpp
- WSRequestHandler.h
Implements ToggleMute (inverts source's mute) and SetMute (sets mute to true or false).
> Add mute source commands

- PROTOCOL.md
- Utils.cpp
- Utils.h
- WSRequestHandler.cpp
- WSRequestHandler.h
I took some of your ideas from your rtmp-settings branch and combined them with my prior changes.  Your access of the service configuration via the output stream was actually not required (see the code changes),
I decided to simplify some of the names of things and just go with "StreamSettings" as the term used in the protocol in the tab inside OBS Studio settings is called "Stream".
I have added GetStreamSettings, SetStreamSettings, and SaveStreamSettings requests (the "SaveStreamSettings" can also be achieved with a  'save' request parameter on the SetStreamSettings call).  This allows you to (on disk or only in memory) change the streaming server settings. SetStreamSettings takes in the same structure as the response from GetStreamSettings and also supports "patch" like operations as …
> Custom stream settings

- PROTOCOL.md
- WSRequestHandler.cpp
- WSRequestHandler.h
Use case: Reset media sources for recovery of timed-out input streams.
> Protocol: add ResetSceneItem for resetting source items

- PROTOCOL.md
- WSRequestHandler.cpp
- WSRequestHandler.h
Adds those 2 request types for the functions "obs_source_set_sync_offset" and "obs_source_get_sync_offset". We plan to gracefully auto adjust an audio source delay to match a twitch stream (based on its delay). So this would be great to have!
> Add request types: SetSyncOffset and GetSyncOffset

- WSRequestHandler.cpp
`SetHeartbeat` is the name of the request, `HandleSetHeartbeat` was the method name.
> docs: HandleSetHeartbeat -> SetHeartbeat

- WSRequestHandler.cpp
This commit makes saving the replay buffer not rely on whether or not a hotkey is set in OBS.
This is a temporary follow-up to PR #104, issue #90, and [OBS Mantis Bug 955](https://obsproject.com/mantis/view.php?id=955) until the OBS Frontend API gets a built-in function for this.  I am also working on that, which is why I called this temporary.  However, PRs to OBS core may take longer to get merged than a PR here, so I'm submitting this PR for now.
Also, I couldn't see an easy way to detect a success/fail from OBS on saving the replay, so I made the function here simply return an OK message.  The only way right now to detect if a reply was saved would be to manually check if the file exists.
I've compiled and tested this on Windows 10 Pro 64-bit.  I wasn't sure about the commit …
> Fix saving replay buffer when no hotkey is set

- Config.cpp
- Config.h
- Utils.cpp
- Utils.h
- WSEvents.cpp
- WSEvents.h
- WSRequestHandler.cpp
- WSRequestHandler.h
- forms/settings-dialog.cpp
- obs-websocket.cpp
- obs-websocket.h
I've undergone a rewrite of some of obs-websocket's internals:
- Rewrite variable names to camelCase
- Use `obs_data_t*`, `obs_source_t*`, `obs_output_*` and others in special wrapper classes that automatically call their associated `release` function.
Current `release` code:
```cpp
void dummy() {
obs_data_t* data_obj = obs_data_create();
obs_data_set_string(data_obj, "key", "value);
obs_data_release(data_obj);
}
```
New proposed `release` code:
```cpp
void dummy() {
OBSDataAutoRelease dataObj = obs_data_create();
obs_data_set_string(dataObj, "key", "value);
}
```
The goal of this rewrite is to unify code style, make easier the use of OBS' API and reduce the number of potential memory leaks. The auto-releases classes are named are based on `OBSRef` from libobs' C++ helpers in `obs.hpp`. …
> Automatic function-scope OBS instance release + refactor variable names to camelCase

- docs/docs.js
- src/WSRequestHandler_Sources.cpp
Wrote this glob originally to avoid accidentally pulling in the third party `deps` directory.
> docs: update glob to account for relocation to src

- CI/generate-docs.sh
- docs/comments.js
- docs/config.json
- docs/docs.js
- docs/protocol.hbs
Realized that the `generate-docs.sh` script wasn't erroring out by mistake.
> docs: fail CI build if documentation is invalid

- src/WSRequestHandler_Sources.cpp
OBS distinguishes differentiates between the url and the local_file. This is now taken into account.
> Added the local_file path to the Browsersources

- src/Utils.cpp
When using 'SetRecordingFolder', it will fail if the folder does not already exist. If one wants to save recordings to changing folders (such as a different folder for each game), this is not possible without running an extra program/script.
This pull request changes obs-websocket to try to create the directory (and all intermediaries) when using 'SetRecordingFolder' to solve this issue.
> Create folder for 'SetRecordingFolder' if it does not exist

- src/WSRequestHandler_SceneItems.cpp
- src/WSRequestHandler_Sources.cpp
`char*` to `QString` for string comparison == operator
`SendOKResponse` to send the object properly
> fixing delete scene item response and setting sceneitem bounds

- CI/install-setup-qt.cmd
- appveyor.yml
Official OBS releases have switched to Visual Studio 2017 and Qt 5.10.1. There is no 32-bit Qt 5.10.1 package for Visual Studio 2017, but the Visual Studio 2015 package is compatible.
The biggest thing required to do this on AppVeyor is to specify the Visual Studio 2017 image.  You can see from the CI results on my fork ([here](https://github.com/RytoEX/obs-websocket/commits/vs2017qt510), while it exists) or from the [AppVeyor build history](https://ci.appveyor.com/project/RytoEX/obs-websocket/build/1.0.51) that it builds correctly.
> CI(Windows): Use Visual Studio 2017

- CI/build-macos.sh
- CI/install-build-obs.cmd
- CI/install-dependencies-macos.sh
- CMakeLists.txt
- appveyor.yml
This PR is a series of general CI and CMake improvements.
This PR adds support for the build config/type "RelWithDebInfo", which is what OBS uses for its official releases, and it sets the default build config to that.  This PR has also shown a reduction in CI build times of 1-5 minutes depending on CI service, CI status/availability, and whether a full OBS build is needed.
I still have some macOS specific CI/CMake changes I'd like to work on, but I figured I'd submit these first, so this PR can be considered separately from those later changes.  These changes build locally and on CI, and obs-websocket seems to work when run through some simple tests with the t2t2 web client.
> CI and CMake improvements

- .travis.yml
- CI/install-build-obs-macos.sh
- CI/install-dependencies-macos.sh
This PR does several things:
* Update Packages to 1.2.3 to keep CI running correctly
* Update Qt to latest in brew (this is what OBS Studio CI does)
* Build the most recent OBS Studio git tag (as of this date 21.1.1)
* Move the obs-studio build task to a separate script (creates a separate section in CI logs, and lets user skip the obs-studio build script if building locally with scripts)
I have more macOS CI changes in the pipeline, but I'm struggling with a few of them, so I thought I'd split these off since they seem stable.
The obs-studio build script could probably use a bit of directory/path checking to make sure it's changing into the correct directory, but that should only be a concern if using the scripts locally, and I don't have access to a Mac to test locally.
On the note of …
> macOS CI updates

- BUILDING.md
This PR updates the building instructions to account for the newer Qt version, adds some links for convenience.  There is a second commit which wraps some longer lines to 80 characters to make it easier to read them in text editors.  I only included it as a separate commit to make it easier to see the actual content changes in the first commit, but these are intended to be squashed together (assuming that the word-wrapping is preferred/wanted at all).
It might be helpful to include a note that the Qt version should match what obs-studio uses, I just wasn't sure how to phrase it and where to put it.
> Build instruction update

- BUILDING.md
- CI/build-macos.sh
- CI/package-macos.sh
- CMakeLists.txt
This PR adds some fixes mostly meant for people that build obs-websocket themselves using the CI scripts, which boil down to "don't fail when running the script a second time because the first try failed".
Included are some minor cleanups for `dyld` runtime path handling, making sure no build environment path artifacts are baked into the binaries produced. The current behavour may screw library loading up for people that happen to have something installed in the same paths as the travis environment, which basically boils down to having Qt 5.10.1 installed via homebrew (whether or not this is due to building obs-websocket yourself).
I tried to make the commit messages as explanatory as possble. If you have any further comments please let me know.
> MacOS Build fixes

- CI/macos/qt.rb
As described by in https://github.com/Homebrew/homebrew-core/issues/27095, it is impossible to build QT 5.10 on any macOS newer than macOS 10.12 due to it using C++ 17 by default.
As explained in the issue, the changes outlined in https://github.com/Homebrew/homebrew-core/pull/27139 need to be applied to the Homebrew formula. With those QT 5.10 builds successfully and the result obs-websocket build at least loads without issue in OBS 22.0.3 under macOS 10.14.
> CI: Fix QT 5.10 not building under macOS 10.13+

- CI/install-dependencies-macos.sh
wget is not installed by default, so when doing the build on a fresh machine, brew install it first
> Add wget to install-dependencies-macos.sh

- src/WSRequestHandler_Sources.cpp
Pulled out duplication functionality to mirror [AddSource](https://github.com/obsproject/obs-studio/blob/868796e3a4e781ec8928547198fe3e47a6c4d716/UI/window-basic-source-select.cpp#L87) and added it into graphics context
Removed a AutoRelease that was unintentionally releasing sources more times than necessary and triggering crashes.
@Palakis Looking for feedback on fix and styling and want to test it a bit before merge. Will update if I am confident or find more issues.
> DuplicateSceneItem bug fix

- .travis.yml
- CI/build-macos.sh
- CI/install-build-obs-macos.sh
- CI/install-dependencies-macos.sh
- CI/macos/qt.rb
- CI/package-macos.sh
As discussed in https://github.com/Palakis/obs-websocket/issues/238 this PR updates the build scripts for macOS.
I added some dependency checks and cleaned-up Homebrew handling. The build-files also use the same QT build as obs-studio itself (checked their CI scripts, they install from the same remote formula). This speeds up building (as QT is "poured from a bottle") and ensures compatibility - for now.
I've also updated the bundled QT5 formula to match the remote one, but also added the necessary patches to make it build on macOS 10.13+.
Additionally the scripts now "pin" qt to the installed version, to avoid `brew upgrade` from upgrading it to 5.12.
> 4.4 macOS build system update

- src/WSEvents.cpp
- src/WSRequestHandler_SceneItems.cpp
- src/WSRequestHandler_Sources.cpp
- src/WSRequestHandler_Streaming.cpp
Fixed several typos throughout the project on the 4.3-maintenance branch.
This mostly the same as #247, but GitHub said the PR for one branch could not be automatically merged into the other, so I'm filing a separate PR so you don't have to do the legwork.
> general: Fix several typos throughout

- CI/install-dependencies-macos.sh
Just two quick fixes I made while building a package today:
* Added a missing comma to get the project to compile again
* Added a check for already-installed `packagesbuild` in the CI script for macOS dependencies
> Fix compile error and added dependency check in build script

- docs/generated/comments.json
- docs/generated/protocol.md
- src/WSRequestHandler_Scenes.cpp
This small change is all that is needed to get the [typedef generator for obs-websocket-js](https://github.com/haganbmj/obs-websocket-js/pull/126) working again. Unfortunately, I think we need to cut a new release of `obs-websocket` once this gets merged, as the build process for `obs-websocket-js` is currently built to look at whatever the latest release tag is here on GitHub for `obs-websocket`, and I'd like to avoid making it look at a specific commit or something similar.
> docs(jsdoc): clean up types for compatability with obs-websocket-js typedef generator

- CI/install-build-obs-macos.sh
- CI/install-build-obs.cmd
- src/WSRequestHandler.cpp
- src/WSRequestHandler.h
- src/WSRequestHandler_Streaming.cpp
Added a handler that allows sending text as captions through OBS' built-in caption functionality.
I wasn't sure where to add it, so I just put it into streaming.
Also I hacked together a little demo site: https://rodney.io/stuff/obscaptions/ Just click the mic and it will (try to) connect to OBS and start sending captions. It would need a lot more work to be useful, but it works.
> Add caption handler

- src/Utils.cpp
- src/Utils.h
- src/WSEvents.cpp
- src/WSEvents.h
- src/WSRequestHandler_SceneItems.cpp
Feature request
Current when a source on a scene is resized or moved there is no event to notify socket subscribers that this occured. OBS does emit `item_transform` for this.
Clone OnSceneItemAdd to a new function to support the `item_transform` signal. Emit as `SourceItemChanged`
Basically here I've just duplicated and adjusted `OnSceneItemAdd` to match the existing format.
Personally I'd extend to emit the details about the scene. But this doesn't match what the other events do in OBS-Websocket in this group.
> Support item_transform signal

- docs/generated/comments.json
- docs/generated/protocol.md
- src/WSRequestHandler_Sources.cpp
The API call listed in the documentation doesn't work (tested on 4.3.1),
but without the 's', it works fine. Update documentation to match code.
> Fix call name GetSourcesTypesList -> GetSourceTypesList

- src/Config.cpp
- src/Config.h
- src/Utils.cpp
- src/Utils.h
- src/WSEvents.cpp
- src/WSEvents.h
- src/WSRequestHandler.h
- src/WSRequestHandler_General.cpp
- src/WSRequestHandler_Profiles.cpp
- src/WSRequestHandler_Recording.cpp
- src/WSRequestHandler_ReplayBuffer.cpp
- src/WSRequestHandler_SceneCollections.cpp
- src/WSRequestHandler_SceneItems.cpp
- src/WSRequestHandler_Scenes.cpp
- src/WSRequestHandler_Sources.cpp
- src/WSRequestHandler_Streaming.cpp
- src/WSRequestHandler_StudioMode.cpp
- src/WSRequestHandler_Transitions.cpp
- src/WSServer.cpp
- src/WSServer.h
- src/forms/settings-dialog.h
- src/obs-websocket.cpp
> events refactor (transitions & scene signals) + new events

- docs/generated/comments.json
- docs/generated/protocol.md
- src/Utils.cpp
- src/WSRequestHandler_SceneItems.cpp
Lockedness can be seen when you query an item or see the scene
contents, and can be changed (only) with SetSceneItemProperties.
> Allow the manipulation of the locked flag of scene items.

- test/package-lock.json
- test/package.json
`obs-websocket-js` now includes typedefs directly in the package, so `obs-websocket-js-types` is deprecated and no longer necessary.
`obs-websocket-js` requires a pretty modern version of TypeScript, so I've also updated the `typescript` and `ts-node` dependencies to match.
> chore: update test dependencies

- src/Utils.cpp
After upgrading both OBS and obs-websocket, I got segfaults every time a websocket client connected. My analysis pointed to a problem in Utils.cpp GetTrayIcon returning a non-null but invalid pointer (0x20 in my tests), which appeared to happen when there was no system tray icon.
Not sure if this is a true fix or not, but it does appear to stop the crashes.
> Return nullptr if there are no tray icons

- src/WSRequestHandler.cpp
- src/WSRequestHandler.h
- src/WSRequestHandler_Sources.cpp
Provides a new `GetSourceImage` method that:
- Takes an image snapshot of the specified source
- Encodes it as a PNG and/or WebP picture and sends it to the WebSocket client as a base64 data URI
Todo: 
Closes #169
> Source Image Snapshot

- docs/generated/comments.json
- docs/generated/protocol.md
- src/WSRequestHandler.cpp
- src/WSRequestHandler.h
- src/WSRequestHandler_General.cpp
I'm not sure that this is the best way to do it, nor if it's the best place to put this code. But it's a start.
Implements #296.
> Create an endpoint to view basic video info eg canvas size

- src/Utils.cpp
- src/WSEvents.cpp
- src/WSRequestHandler_SceneItems.cpp
- src/WSRequestHandler_Scenes.cpp
- src/WSRequestHandler_StudioMode.cpp
- Bonus: fix deprecated request types: SetSceneItemRender, SetSceneItemPosition, SetSceneItemTransform, SetSceneItemCrop
Fixes #237
> Groups fixes

- CMakeLists.txt
- src/WSRequestHandler.cpp
- src/WSRequestHandler.h
- src/WSRequestHandler_Outputs.cpp
Request types:
Events: not possible yet, no global signals for outputs are available.
Closes #274
> Outputs API

- src/WSEvents.cpp
- src/WSEvents.h
- src/WSRequestHandler.cpp
- src/WSRequestHandler.h
- src/WSRequestHandler_General.cpp
This PR adds a new function "BroadcastWebSocketMessage" which takes two parameters: realm and data. realm is intended to be a user-defined string to distinguish the source/recipient/scope of the message and data is the actual message.
Why?
With this change for example a javascript code in a browser source can connect to the websocket server and can receive such Messages and act upon them. This makes it possible for example to write some remote controlling software which triggers actions in a browser source without the need for any additional server.
> Make it possible to broadcast messages (data) to other websocket clients

- src/WSRequestHandler_General.cpp
Unfortunately your fix broke it. These are params, not returns.
> Fix spec of HandleBroadcastCustomMessage

- src/WSRequestHandler_Sources.cpp
based on the request at https://github.com/bazukas/obs-linuxbrowser/issues/46 I did a quick search for the string "browser_source" and these seem to be the only two occurrences. Enhancing the conditional with the identifier of the obs-linuxbrowser plugin, this should solve the problem.
As I'm currently not at home, I can't verify this does what it should, but I will test it later tonight.
@mjc666 if you are still interested please give it a test run to verify if these two plugins work together now.
> allow for "linuxbrowser_source" to be controlled

- src/WSServer.cpp
Because that's what websocketpp does if you call send(hdl, msg, opcode) instead of send(hdl, msg, opcode, errorCode)
Closes #359
> WSServer: handle error codes to avoid throwing exceptions when sending a message

- src/Utils.cpp
- src/Utils.h
- src/WSEvents.cpp
- src/WSEvents.h
- src/WSRequestHandler.cpp
- src/WSRequestHandler.h
- src/WSRequestHandler_Recording.cpp
- src/WSRequestHandler_Streaming.cpp
Changes & additions:
Closes #370
> Recording Pause support

- src/WSRequestHandler_Sources.cpp
Revise the wording of `TakeSourceScreenshot` to note that if you specify a scene name, you get the scene.
Sorta #383
> Take scene screenshot

- CI/package-macos.sh
> ci(macos): fix lookup path of Qt dependencies for new OBS bundle format

- src/WSRequestHandler_Streaming.cpp
Bug: Current implementation of `HandleSendCaptions` uses `obs_output_output_caption_text1` to send caption text but `obs_output_output_caption_text1` has a hardcoded delay of 2 seconds before sending the captions text. 
Here the code:
```
void obs_output_output_caption_text1(obs_output_t *output, const char *text)
{
if (!obs_output_valid(output, "obs_output_output_caption_text1"))
return;
obs_output_output_caption_text2(output, text, 2.0f);
}
```
This leads to the captions being out of sync with video and continues to get out of sync as subsequent calls to send captions will have to wait in a queue with the other delayed text.
To solve this issue, instead of using `obs_output_output_caption_text1` switch to using `obs_output_output_caption_text2` with a 0 second delay so captions are in …
> Switch from using caption_text1 to caption_text2

- src/WSEvents.cpp
> WSEvents: fix recording time field after refactoring

- src/WSEvents.cpp
This field reports the type of the transition (`obs_stinger_transition`, `fade_to_color_transition`, etc), which can be useful for code which needs to react differently depending on what type of transition is being played.
Of note is that OBS calls this an `id`, but I think that's kind of a misleading name. `type` seems like a more semantic name for this information to me, but I'm open to changing it if we want to stay consistent with the nomenclature that OBS itself uses.
> feat(events): add "type" field to TransitionBegin

- src/Utils.cpp
- src/WSEvents.cpp
Some transitions, such as Stingers, have a fixed duration. There is currently no way to retrieve this value from the API, and `obs-websocket` will currently return an incorrect value when one of these transitions begins.
For now, I think it is better to explicitly return -1, which is a better indicator that we have no idea what the real duration is, instead of a misleading number which users might think looks correct at first glance.
Related to #408
> fix(events): don't advertise a false duration for fixed transitions

- src/WSRequestHandler_Streaming.cpp
This fixes #378 by applying the stream settings where currently it defines the service and responds with the data of that service object, but does not actually apply it. This also changes the behavior of the response to read the result of the change (as if you called getstreamsettings), which should mean that if the change was not successful, the response object should differ from the request object.
> Fix SetStreamSettings when switching type

- src/WSEvents.cpp
- src/WSEvents.h
NOTE: This is a placeholder PR and not for merging.
It would be extremely convenient to be able to get a websocket event whenever an item's locked status is toggled (parallel to the item visibility toggle event).
Not possible with current OBS as there is no libobs event to hook (this websocket event will simply never fire).
Upstream feature request is tracked here: https://obsproject.com/mantis/view.php?id=1463
> Fire an event whenever an item is locked/unlocked

- docs/generated/comments.json
- docs/generated/protocol.md
- src/WSRequestHandler.cpp
- src/WSRequestHandler.h
- src/WSRequestHandler_General.cpp
Depends on obs-studio#1910 for back end functionality.
Is there a convenient and safe way to have this return a tidy error message if OBS doesn't support obs_frontend_open_projector()?
Closes #214
> Create a command for opening a projector.

- docs/generated/comments.json
- docs/generated/protocol.md
- src/Utils.cpp
- src/WSRequestHandler_SceneItems.cpp
Now that the alignment/gravity of visual scene items is being transmitted, the only part of #356 still remaining is to add a 'muted' flag to aural scene items. This allows a client to easily see which entities are currently muted when querying with GetSceneItems or seeing the full scene details in SwitchScenes; the status can already be updated by the SourceMuteStateChanged event.
Replaces PR #356.
> Add a 'muted' flag to GetSceneItems

- src/Utils.cpp
- src/Utils.h
- src/WSEvents.cpp
- src/WSEvents.h
Adds events for `TransitionEnd` and `TransitionVideoEnd`.
`TransitionVideoEnd` is specific to Stinger transitions. It is fired when their video has actually completed playback. This is important, because `TransitionEnd` is fired at the cut point of the Stinger, which is nice to have but isn't always what the user might want.
This builds on #409, and should be merged after it.
> feat(events): add "TransitionEnd" and "TransitionVideoEnd" events

- src/Utils.cpp
- src/Utils.h
- src/WSEvents.cpp
- src/WSRequestHandler_SceneItems.cpp
I went through the spec of all scene item request types and events. All scene items events are fine. There are three request types to fix:
In these three request types, allow the `item` param to either be:
- A string, targeting the first scene item available by this name (current/legacy behaviour)
- An object, borrowing the spec used for the `item` request field in [`DeleteSceneItem`](docs/generated/protocol.md#DeleteSceneItem) and [`DuplicateSceneItem`](docs/generated/protocol.md#DuplicateSceneItem)
Fixes #154
Fixes #398
> Target Scene Items per ID, in addition to scene name and source name

- docs/generated/protocol.md
- src/WSRequestHandler_Scenes.cpp
For some reason the link to the `GetCurrentScene` section of the docs was put into a codeblock
> [Docs] Fix link to GetCurrentScene

- README.md
I've created a simple async Python library for people who just want the simple stuff. Figured I would add it here.
> Add simpleobsws to list of language APIs

- CI/install-build-obs-macos.sh
According to [this](https://github.com/obsproject/obs-studio/blob/master/UI/frontend-plugins/frontend-tools/CMakeLists.txt#L73), captions support is not available on MacOS (apparently it uses windows-only apis, so we should not build it here.
> [Bug Fix] Don't build with captions on MacOS

- src/WSServer.cpp
Regardless of whether debug is enabled or disabled, websocketpp seems to dump its log messages into the OBS console. These are annoying and clutter up logs. They are also redundant if debug logging is enabled.
> Suppress websocketpp logging entries

- src/WSRequestHandler_Sources.cpp
OBS appears to be using a new format for the FreeType2 source, so we add the new kinds.
One thing I'm unsure on is if anything still uses the old naming stuff `text_ft2`/`text_ft2_v2`, since if not then we should not check.
> [Bug Fix] Fix FreeType2 source type recognition

- README.md
I've created a simple Python 3 script which provides HTTP API endpoints for obs-websocket requests.
My motivation is that as I've seen a lot of requests for some kind of HTTP api to be available with obs-websocket. This is an interim solution to the call.
> Add obs-websocket-http

- src/WSRequestHandler_Sources.cpp
Both of these requests are doing essentially the same thing as `GetSourceSettings` and `SetSourceSettings`, so there is no reason to have the extra bloat.
> Deprecate SetBrowserSourceProperties and GetBrowserSourceProperties

- src/WSRequestHandler_StudioMode.cpp
As talked about in #144 this adds a check to `EnableStudioMode` and `DisableStudioMode` in order to be consistent with `StartRecording`/`StopRecording`
EDIT: I would also argue that this is not a breaking change, since correct implementations of these requests should not induce the error.
> Add error system to EnableStudioMode and DisableStudioMode

- BUILDING.md
- CI/build-ubuntu.sh
- CMakeLists.txt
After #478, building on Ubuntu was broken. This adds a flag for Ubuntu users which installs the plugin binaries into the correct directory.
> Fix install dir on Ubuntu by using new cmake flag

- src/WSRequestHandler.cpp
- src/WSRequestHandler.h
- src/WSRequestHandler_Transitions.cpp
Gets the current position of the active transition. Works on manual and also auto transition modes. Originally added to #439 but removed since #439 requires OBS changes and wont be ready for 4.8.
> Requests: Add GetTransitionPosition

- src/WSRequestHandler_Sources.cpp
Gives a better, built-in option for people to use decibels of attenuation instead of amplitude. Default response/request format is amplitude.
Resolves #441
> Requests: Add useDecibel bool to GetVolume and SetVolume

- src/WSRequestHandler_Sources.cpp
Adds `fileFormat` to save the file with a specific picture format (ignoring filename)
Adds `compressionQuality` to specify a specific compression quality. This mainly depends on the picture format used, as to how much it controls.
Supported image formats can be viewed using `GetVersion`: `supported-image-export-formats`
Closes #473
> Requests: Add new parameters to TakeSourceScreenshot

- src/WSEvents.cpp
Since sources in OBS are also scenes, provide the user a string
so that they can differentiate.
> Events: Add sourceType string to SourceRenamed

- src/WSRequestHandler.cpp
- src/WSRequestHandler.h
- src/WSRequestHandler_Sources.cpp
Adds the `SetSourceName` request which can be used to rename sources.
Also works on scenes since scenes in OBS are also sources.
Closes #507
> Requests: Add SetSourceName (renaming sources)

- CI/install-build-obs-macos.sh
This reverts #477. OBS on MacOS supports closed caption encoding. The Windows-only dependencies [here](https://github.com/obsproject/obs-studio/blob/master/UI/frontend-plugins/frontend-tools/CMakeLists.txt#L73) are only related to audio capture, not closed caption encoding.
OBS Studio 25.0.8 and latest version of obs-websocket 4.x built with `BUILD_CAPTIONS=true` receiving an event originating from obs-websocket-js:
```
20:14:31.677: [obs-websocket] Request >> '{"text":"hello world! Mon Jun 29 2020 20:14:31 GMT-0500 (Central Daylight Time)","request-type":"SendCaptions","message-id":"39"}'
20:14:31.677: [obs-websocket] Response << '{
20:14:31.677:     "message-id": "39",
20:14:31.677:     "status": "ok"
20:14:31.677: }'
```
Closed captions appearing in Twitch stream:
> [Bug Fix] Reenable building with captions on MacOS

- src/WSRequestHandler_Sources.cpp
When the volume in OBS is -infinity, `GetVolume` returns a decibel value of
either 0, or in some cases no `volume` property at all. This makes `GetVolume`
return a decibel value of -100.0 if the real volume is -infinity.
Fixes #528
> Requests: Fix useDecibel response when volume is -infinity

- .github/workflows/pr_push.yml
- CI/macos/Brewfile
This PR adapts current CI scripts for use with Github Actions. As the workflow is not relying on the existing scripts, it can be tested and used independently from current CI implementation.
Further notes:
* Workflow was tested on my own fork, artifacts were checked on macOS and Windows
* This workflow only runs CI for pull requests and pushes to the current main branch `4.x-current` - there is an additional pull request just for tags/releases
* Currently only prior OBS builds on Windows (32bit&64bit) are cached between runs, as I couldn't get the same functionality to work on macOS or Linux (even with caching Windows builds are still the slowest)
* Artifacts are generated for every run, macOS artifacts are unsigned
* Artifact naming scheme is `obs-websocket-SHORT_COMMIT_HASH-OS` with …
> CI: Add Github Actions workflow for PRs and pushes to main branch

- .github/workflows/tag_release.yml
- CI/macos/Brewfile
This PR adapts parts of current CI scripts for use with Github Actions. As the workflow is not relying on the existing scripts, it can be tested and used independently from current CI implementation.
Further notes:
* Workflow was tested on my own fork, artifacts were checked on macOS and Windows
* This workflow only runs when a commit is tagged with a common version (currently major version 4 or 5 is included in the trigger)
* Currently only prior OBS builds on Windows (32bit&64bit) are cached between runs, as I couldn't get the same functionality to work on macOS or Linux (even with caching Windows builds are still the slowest)
* Artifacts are generated for every run, macOS artifacts are *signed* with given secrets stored in Github
* `MACOS_CERT_CODESIGN` - installer and application …
> CI: Add Github Actions workflow for release tags

- src/WSEvents.cpp
- src/WSEvents.h
- src/WSRequestHandler.cpp
- src/WSRequestHandler.h
- src/WSRequestHandler_Sources.cpp
This is used to determine whether a Browser source has "Control audio via OBS" enabled. If true, the source should appear in a mixer.
> Requests, Events: Add support for Audio Active

- README.md
- SSL-TUNNELLING.md
Moves ssl tunnelling instructions to its own .md
Having the SSL tunneling instructions on the README caused clutter and was
unnecessary. 
-   [x ] I have read the [**contributing** document](https://github.com/Palakis/obs-websocket/blob/4.x-current/CONTRIBUTING.md).
-   [ x] My code is not on the master branch.
-   [ x] The code has been tested.
-   [ x] All commit messages are properly formatted and commits squashed where appropriate.
-   [ x] I have included updates to all appropriate documentation.
> Docs: Move ssl tunnelling guide to its own page

- src/WSRequestHandler_Sources.cpp
Change TakeSourceScreenshot to take the currently active scene if no source name is provided.
Allows clients to get a screenshot of the current "master" image without having to track or query current scene.
Tested OS(s): Linux
Enhancement (modification to a current event/request which adds functionality)
> TakeSourceScreenshot: default to current scene

- CMakeLists.txt
Adding the -mfpu=neon flag to the arm target so that it can build on arm devices like raspberry pi
With the merge of pr [#3180 on obs-studio](https://github.com/obsproject/obs-studio/pull/3180), we can now build and install the plugin for raspberry pi and other arm devices.  It will fix the following issue:
Tested OS(s): 
I ran the code on a Raspberry Pi 3B+ running Raspberry Pi OS 2015-05-05 with this [build script](https://github.com/venepe/install-obs-raspberry-pi.git).  I also ran it on a MacBook running Catalina.
-   [x] All commit messages are properly formatted and commits …
> CMakeLists: Compile for arm targets

- src/Utils.cpp
Fixes a crash happening in `Utils::GetTrayIcon` by refactoring it to remove the old Qt `findChildren` hack and using `obs_frontend_get_system_tray` instead.
Fixes #569 
Tested on Windows 10 2004 with t2t2's obs-tablet-remote and tray notifications enabled.
> Utils(GetTrayIcon): refactor with frontend API function

- src/WSRequestHandler_Scenes.cpp
The requests had `unreleased` marked, leading people to think that the already-released requests were coming in v4.8.0
- Bug fix (non-breaking change which fixes an issue) 
> Docs: Fix requests marked as "unreleased"

- installer/installer.iss
More info here: https://jrsoftware.org/ishelp/index.php?topic=setup_direxistswarning
The installer prompts `The directory ... already exists. Would you like to install to that directory anyway?` when running the installer, which may confuse users.
> Installer: Don't show warning when obs directory is not empty

- src/Utils.cpp
- src/Utils.h
- src/WSRequestHandler_Profiles.cpp
- src/WSRequestHandler_SceneCollections.cpp
For `SetCurrentProfile` and `SetCurrentSceneCollection`, check if it exists before attempting to switch to it, and return an error if it does not exist.
Because the code told me to
> Requests: Scene collection and profile name checking

- src/WSRequestHandler.cpp
- src/WSRequestHandler.h
- src/WSRequestHandler_General.cpp
This PR adds two new requests that allow triggering hotkeys callback functions over websocket. The hotkey can be defined either by its unique name (the one used during registration) or by specifing the combination of keys associated to trigger it. In the latter, if the same combination has been set for multiple hotkeys, all of them will be triggered.
_Note_: the requests are named `ProcessHotkey `and not `PressHotkey` because no "physical" pressing event is sent/triggered, rather just the underlying callback functions are called/processed. Please let me know if you'd rather name the requests differently.
This PR was motivated by the need to trigger script functions remotely. The requests can be easily used to trigger custom hotkeys registered within a script, and of course they also work …
> Requests: Add hotkeys press events

- src/WSRequestHandler_SceneItems.cpp
Makes `GetSceneItemList` look for scene items in the current scene if the `sceneName` parameter is not specified.
Making it more in line with how the scene item functions behave with their scene name parameter. 
Tested on Windows 10 2004 with OBS 25.0.8
> requests(GetSceneItemList): fallback to current scene if sceneName is not specified

- src/WSRequestHandler.cpp
- src/WSRequestHandler.h
- src/WSRequestHandler_Sources.cpp
- src/WSRequestHandler_Transitions.cpp
This pull request adds methods to get and set transition settings (e.g.: change a stinger's video file).
It also fixes the behaviour of `SetSourceSettings`: instead of uselessly merging the current and updated settings together itself, it now relies on the same exact behaviour that libobs' does natively when calling `obs_source_update`.
Like sources, transitions have settings. Actually, under the hood transitions _are_ sources. The thing is, currently there's no way to update transitions programmatically, as they are not exposed in the results of `GetSourcesList`. This pull request aims to address this situation.
Tested on OBS Studio v26 master running on Windows 10 64-bit …
> Get/Set Transition Settings

- src/WSRequestHandler_Outputs.cpp
Fixes a crash when trying to use GetOutputInfo, StartOutput or StopOutput commands.
Fixes #553 
Tested OS(s): Windows 10 20H2
> requests(outputs): fix corrupted parameters object on MSVC when using findOutputOrFail

- src/WSEvents.cpp
Modifies the following events to provide the new state of their respective entity:
Fixes #380
Tested OS(s): Windows 10 20H2
> Events: provide new state of entity (in events that don't do it already)

- README.md
Add a link to obs-cli on the README. obs-cli is a tool to control OBS from the command-line, based on obs-websocket through obs-websocket-js.
This is similar to the obs-websocket-http listed right above it: a wrapper to operate obs-websocket from a different interface (in this case, the command-line interface).
obs-cli is written in Node.js, so it should be cross-platform.
Tested OS(s): macOS
- Documentation change (a change to documentation pages): A change to the `README`.
-   [x] All commit messages are properly formatted and commits squashed where appropriate. **I’m not sure what …
> Add link to obs-cli

- src/WSRequestHandler_Sources.cpp
Allow volumes > 1.0 / > 0dB, which is legal in OBS (you can do this in Advanced Audio Properties). OBS allows up to +26dB gain, so we do the same. This corresponds to approximately 20x linear gain (actually 19.9526231497, but 20 is easier to explain and OBS doesn't care).
This is required to be able to add audio gain to sources that have too low an audio level.
A previous version of this patch was tested with OBS master a few months ago, and used in production. I've rebased this on the current version, which added the decibel mode. I think the change is obvious enough that it does not warrant further testing.
-   [x] I have read the [**contributing** …
> Requests: SetVolume: allow volumes > 1.0

- CMakeLists.txt
Files in the Debian/Ubuntu package are all chmod'ed to 777 (read/write to everyone). This shouldn't be the case.
Fixes #620 
Checking permissions by reading the generate Debian package with 7-Zip on Windows 10.
> ci(linux): fix deb package file permissions

- src/WSEvents.cpp
Stop the `WSServer` when receiving the OBS Exit event.
I have run into crashes on OBS exit due to websocket clients responding to events during teardown. This should fix it by reacting to the exit event and stopping the server.
Tested OS(s): 
* macOS 10.15.7
> Stop WSServer on OBS exit

- src/WSRequestHandler_Scenes.cpp
Looks like we accidentally let the `CreateScene` `@since` version be 4.8.0, even though it was merged after the release.
Fixes #642 
Reduce confusion
> Requests: Fix wrong docs version for CreateScene

- docs/generated/comments.json
- docs/generated/protocol.md
- src/WSRequestHandler_SceneCollections.cpp
Adds a ScenesCollection object in the protocol definition,
replacing the current Array<String> return  with
Array<ScenesCollection>, keeping it more coherent with
other requests that return objects in the same format.
This will help automated code generation from comment.json
that otherwise would require ad-hoc handling for that specific
request.
Signed-off-by: Valter Minute <valter.minute@gmail.com>
Added new typedef and changed @return of WSRequestHandler::ListSceneCollections to generate a new object type named ScenesCollection instead of using string.
The changes impacts only generated documentation and comments.json, since the request already returns an array of objects.
This change will make automated code generation of APIs in other languages more straightforward since the …
> General: Add ScenesCollection object

- src/WSRequestHandler_SceneItems.cpp
This helps to address #624 and solves my particular use-case with minimal new `obs-websocket` code
`item` (an int) can now be passed instead of `source` (string) to `SetSceneItemRender` addressing the situation where the same source has been duplicated in a scene, and hence has the same name.
Verified on my Ubuntu 20.04 laptop - software was built locally using the scripts in the project `CI/` directory
> Request: add ID support for SetSceneItemRender

- src/WSRequestHandler.cpp
- src/WSRequestHandler.h
- src/WSRequestHandler_Sources.cpp
Creates a source to programmatically refresh a browser source. I would have made this earlier if I have just spend more time reading the OBS API docs (I'd have known about `obs_property_button_clicked()` so RIP
Fixes #456 
Twas requested.
> Requests: Add RefreshBrowserSource

- src/WSRequestHandler.cpp
- src/WSRequestHandler.h
- src/WSRequestHandler_General.cpp
- src/WSServer.cpp
- src/protocol/OBSRemoteProtocol.cpp
- src/protocol/OBSRemoteProtocol.h
- src/rpc/RpcResponse.h
Adds a way to execute a set of requests sequentially.
Fixes #134
Tested OS(s): Windows 10 20H2 64-bit
> Batch Requests

- src/WSRequestHandler.cpp
- src/WSRequestHandler.h
- src/WSRequestHandler_General.cpp
New request to induce delay in the processing of `ExecuteBatch`
Adds a new request: `Sleep`
This allows you to delay execution, specifically when using it in `ExecuteBatch`. Example uses:
- `StartStreaming`, sleep 5 seconds, then `GetStreamStatus`, in order to verify that stream was started successfully.
- To perform simple animations like setting scene item visibility, with much higher time accuracy than is possible via multiple websocket requests
Makes `ExecuteBatch` more versatile.
Switched between two scenes with a delay of 1000ms between scene switches.
-   [x] I have read the [**contributing** document](https://github.com/Palakis/obs-websocket/blob/4.x-current/CONTRI …
> Requests: Add Sleep

- src/Utils.cpp
- src/WSRequestHandler_SceneItems.cpp
Adds a filter field to the scale property in both SetSceneItemProperties and GetSceneItemProperties.
When using things like AddSceneItem to dynamically create scene items, the scale filter will always be set to the default of "Disable". Adding this property means that these items can use a different scale filter if the user wishes.
Tested OS(s): Windows 10 x64
-   [x] I have included updates to all appropriate …
> Requests: Add scale.filter to Scene Item Properties

- src/WSRequestHandler.cpp
- src/WSRequestHandler.h
- src/WSRequestHandler_Sources.cpp
Adds SetAudioTracks and GetAudioTracks which allows toggling the audio output of a source to any of the 6 channels.
Wanted to be able to control which source outputs audio to a track dynamically.
Tested OS(s): 
Windows
New request/event (non-breaking)
> Requests: Add SetAudioTracks and GetAudioTracks

- src/WSEvents.cpp
Add volumeDb field to SourceVolumeChanged Event.
Personally I work always with Decibel and when I get a `SourceVolumeChanged` Event, I always have to call `getVolume` (with useDecibel true) in order to get che correct value. This helps me a lot
Tested OS(s): Non tested yet. I except to test it when Azure finishes
-   [ ] The code has been tested.
-   [x] I have included updates to all …
> Requests: Add volumeDb field to SourceVolumeChanged Event

- src/WSRequestHandler.cpp
- src/WSRequestHandler.h
- src/WSRequestHandler_Sources.cpp
Add GetSourceActive to know if a source is being showed in the final fix.
(Copy-pasted from GetAudioActive)
In my context I want to know if a source is shown in the final mix.
This because I use the same sources (microphones) in multiple scenes and I want to know if my voice is audible while streaming / recording.
In my program I have three state for microphones. Active / Muted / Disabled (aka forced muted).
The only method to know if a mic is forced mute for now is to enumerate SceneItems of the current scene (eventually recursively). The method works great but I can't retrieve sources within a group. Other than that, I think it's a more appropriate way to use GetSourceActive.
Tested OS(s): 
Builded with Azure and tested quickly on my Windows 10
- …
> Requests: Add GetSourceActive

- docs/generated/comments.json
- docs/generated/protocol.md
- src/WSRequestHandler_Outputs.cpp
Fix a small typo in the documentation for the `Output` typedef.
Fixes #717
N/A
> Docs: fix typo in output properties

- src/WSRequestHandler_SceneItems.cpp
It has always been an optional bool but was not marked as such.
Fixes #696 
Oops
> Docs: Properly mark `setVisible` as optional

- docs/partials/introduction.md
Fixed URL in introduction.md to correct part of README. (Previous link was dead)
Documentation fix for dead link
Clicked the link :) 
-   [X] I have read the [**contributing** document](https://github.com/Palakis/obs-websocket/blob/4.x-current/CONTRIBUTING.md).
-   [X] My code is not on the master branch.
-   [X] The code has been tested.
-   [X] All commit messages are properly formatted and commits squashed where appropriate.
-   [X] I have included updates to all appropriate documentation.
> docs: fixed url to refer to the correct part of the readme

- src/WSRequestHandler_Scenes.cpp
Autorelease the source created by obs_scene_create() to not leak memory.
Fixes #669 
Creating the scene increments the referenced scene's source by one, but we do not decrement it. This produces a memory leak which leads to the scene never being deleted after being removed from the UI.
> Requests: Release created scene in CreateScene

- src/WSRequestHandler_Scenes.cpp
This patch fixes doc-comment for ReorderSceneItems request, which has the wrong parameter type for `items`.
The parameter `items` accepts a list of SceneItem ids/names but not Scenes.
Found this issue when generating a typed client library.
Tested OS(s): N/A -- this is a documentation fix.
Documentation change (a change to documentation pages)
-   [ ] The code has been tested.
> docs: Fix type of ReorderSceneItems request parameter

- src/WSRequestHandler_Scenes.cpp
Wrap the response of `Utils::GetTransitionFromName` into a `OBSSourceAutoRelease` so that the returned and ref-count increased value is properly decreased and potentially freed after the value moves out of scope.
After some own investigation for my crashes as described in #645 and on Discord I found out that the `Utils::GetTransitionFromName` internally adds a reference count on the returned source (if one is found).
Therefore, if a source was found the reference count is never decreased and causes a crash at shutdown time. I would have just expected a memory leak but it seems to put internals of OBS in a weird state (in my case it made the vlc video source crash).
Tested by running sending the `SetSceneTransitionOverride` command through my [Rust client …
> Requests: Fix leak in SetSceneTransitionOverride

- src/WSRequestHandler_Transitions.cpp
Put the response of `obs_frontend_get_current_transition` into a `OBSSourceAutoRelease` to properly reduce the ref count when it moves out of scope and potentially release the memory.
The memory leak caused the same crashes as to what #761 solves. Somehow the memory leak causes a vlc source and/or browser source to crash.
Ran the related commands with the integration tests of [obws](https://github.com/dnaka91/obws) and confirmed that no crash happened when shutting down OBS.
-   [x] All commit messages are …
> Requests: Fix leak in ReleaseTBar, SetTBarPosition

- README.md
The existing Go client doesn't seem to be supported anymore so I made my own at https://github.com/andreykaipov/goobs for the v4.9.1 protocol, and I plan on updating it when v5 is ready! 😄
Documentation change
> Docs: Add another Go client library

- src/WSRequestHandler_Sources.cpp
Functions were named SetTracks and GetTracks rather than SetAudioTracks and GetAudioTracks as in the actual code, so this mismatch gets picked up by the protocol docs (but not anymore).
Docs were incorrectly listing GetTracks and SetTracks, requests that don't work.
Fixes #789 
Only comment changes, no further compiling or testing done.
-   [ ] The code has been tested.
> WSRequestHandler_Sources: fix comment name for Set/GetAudioTrack

- src/protocol/OBSRemoteProtocol.cpp
- src/protocol/OBSRemoteProtocol.h
Heap corruption fix. Fixes double release on obs_data_t*.
I was debugging a crash and this kept making windbg break execution.
Tested OS(s): Windows 10 20H2
> Protocol: Fix double free of obs_data_t*

- src/requesthandler/rpc/Request.cpp
Currently the `Request::ValidateBasic` function returns an error about missing request data whenever it HAS data. Instead it shoudl return the error when it's missing data.
Many requests failed during testing changes in my client lib and I found this bool check being wrong.
Tested most of the available API requests as part of integration tests for the Rust client library.
-  [x] I have read the [**contributing** document](https://github.com/Palakis/obs-websocket/blob/4.x-current/CONTRIBUTING.md).
-  [ ] My code is not on the master branch.
-  [x] I have included updates to all appropriate …
> Requests: Fix wrong validation in ValidateBasic

- .github/pull_request_template.md
- BUILDING.md
- CMakeLists.txt
- CONTRIBUTING.md
- README.md
- installer/installer-windows.iss.in
- src/eventhandler/EventHandler.cpp
- src/requesthandler/RequestHandler.cpp
- src/requesthandler/RequestHandler.h
- src/requesthandler/RequestHandler_Config.cpp
- src/requesthandler/RequestHandler_General.cpp
- src/requesthandler/RequestHandler_Inputs.cpp
- src/requesthandler/RequestHandler_MediaInputs.cpp
- src/requesthandler/RequestHandler_Record.cpp
- src/requesthandler/RequestHandler_Scenes.cpp
- src/requesthandler/RequestHandler_Stream.cpp
- src/utils/Obs.cpp
- src/utils/Obs.h
Enables the *Changing events. Merge when a version of OBS has been merged with obsproject/obs-studio/pull/5382
- New request/event (non-breaking
> Events: Re-enable *Changing events

- src/eventhandler/EventHandler.cpp
Add missing events for when recording is paused or resumed.
The events were already available in libobs and prepared in obs-websocket, just not connected.
Tested with my `obws` client library and confirmed that the events are fired.
-  [x] I have read the [**contributing** document](https://github.com/obs-websocket/obs-websocket/blob/4.x-current/CONTRIBUTING.md).
-  [ ] My code is not on the master branch.
> Events: Add events for record pause and resume

- docs/docs/partials/introduction.md
Fixed incorrect opcode in introduction.md
Documentation fix for wrong opcode
Clicked the link :)
Documentation change (a change to documentation pages)
-   [X] I have read the [**contributing** document](https://github.com/Palakis/obs-websocket/blob/4.x-current/CONTRIBUTING.md).
-   [X] My code is not on the master branch.
-   [X] The code has been tested.
-   [X] All commit messages are properly formatted and commits squashed where appropriate.
-   [X] I have included updates to all appropriate documentation.
> docs: fixed wrong opcode in docs

- src/requesthandler/RequestHandler_Config.cpp
Adjust the `slotValue` response field of `GetPersistentData` to be of type `Any` instead of `String` (in the docs only!).
The `slotValue` is described to be always a `String` but seeing the code it _seems_ to actually be any possible JSON type.
Tested OS(s): 
> docs: Adjust `slotValue` type to `Any`

- src/requesthandler/RequestHandler_Scenes.cpp
Change the category for all scene related requests to actually be `scenes`.
The `@category` annotation for all scene related requests was `sources` instead of `scenes`, thus they ended up in the wrong category in the generated markdown.
Tested OS(s): 
Adjusted categories and ran `build_docs.sh` to verify the output.
> docs: Correct the category for scene requests

- docs/docs/generate_md.py
Fix the docs generator by replacing `<` with `&lt;` and `>` with `&gt;` for the **Type** column in request and response tables.
The `<` and `>` pair has a special meaning in markdown, being interpreted as HTML tags. That caused the values like `Array<String>` to be displayed as just `Array`. Therefore, they needed to be replaced by their respective `&lt;` and `&gt;` codes.
It is now done for the **Type** column but may need to be extended into other fields that potentially have some form of `<Something>` content.
Ran the `build_docs.sh` script and verified the expected outputs in `protocol.md`.
-  [x] I have read the [Contributing Guidelines](https://github.com/obsproject/obs-websocket/wiki/Contributing-Guidelines …
> docs: Fix `Array` type in markdown

- src/requesthandler/RequestHandler_General.cpp
Add the `supportedImageFormats` field to the docs of the `GetVersion` request.
The field was simply missing from the docs.
Tested OS(s): 
> docs: Add missing `supportedImageFormats` to docs

- src/requesthandler/RequestHandler_Scenes.cpp
Change the type of the `scenes` field of the `GetSceneList` request from `Array<String>` to ~~`Array<Scene>`~~ `Array<Object>`.
Where or how would you like me to document the fields of the `Scene` object?
The request returns an array of scene objects but was documented as returning an array of strings instead.
Tested OS(s): 
> docs: Fix `scenes` type from `String` to `Object`

- CI/macos/build-plugin-macos.sh
Sets the `CMAKE_OSX_DEPLOYMENT_TARGET` option to MacOS version `10.13` for MacOS builds (mostly through ci, but technically for anybody who uses the build scripts).
This is the same as done in the main OBS Studio project.
There have been past reports about obs-websocket not working on older MacOS versions and this setting might eventually fix this. Don't have an old enough Mac to verify this but maybe somebody else who had this issue in the past could try it out?
The seems to be that the CI builds with whatever OS/Xcode version is provided by GitHub and that might have changed between releases in the past. Plus cmake (or rather the Apple clang compiler) seems to use the latest SDK. Therefore, suddenly breaking the builds for older MacOSs due to missing APIs.
Possibly related issues are …
> ci: Set the minimum MacOS version to 10.13

- src/requesthandler/RequestHandler_Inputs.cpp
Document the missing optional `overlay` field of the `SetInputSettings` request.
The field was already available but not part of the documentation yet.
Tested OS(s): 
> docs: Document missing `overlay` field

- src/websocketserver/WebSocketServer_Protocol.cpp
Correct the error message returned when an unknown op code was received.
The error message was formatted as `Unknown OpCode: %s5` but should instead be `Unknown OpCode: 5`, removing the `%s`.
Verified the `%s` is not part of the message anymore when sending an invalid op code through my `obws` library.
> protocol: Fix error formatting for wrong op codes

- src/requesthandler/RequestHandler.cpp
- src/utils/Obs_StringHelper.cpp
Enable the GetRecordDirectory request. Merge when a version of OBS has been released with obsproject/obs-studio/pull/5521
> Requests: Enable GetRecordDirectory

- src/eventhandler/EventHandler.cpp
Enables the *Changing events. Merge when a version of OBS has been merged with obsproject/obs-studio/pull/5382
Second PR since I accidentally had to merge the first one.
- New request/event (non-breaking
> Events: Reenable *Changing events (second time)

- src/requesthandler/RequestHandler.cpp
Enables the `RemoveInput` request. Merge when a version of OBS is released with obsproject/obs-studio/pull/5276
> Requests: Enable RemoveInput

- src/obs-websocket.h
It was a very cool method to save our precious std::strtoll method, but will no longer be needed on the next OBS release.
> Base: Remove old ifdefs

- src/requesthandler/RequestHandler_Inputs.cpp
Enables an availability check in the `SetInputAudioMonitorType` request. Merge when a version of OBS is released with obsproject/obs-studio/pull/5225
> Requests: Add support check for monitoring in `SetInputAudioMonitoringType`

- src/requesthandler/RequestHandler.cpp
- src/requesthandler/RequestHandler.h
- src/requesthandler/RequestHandler_Ui.cpp
Adds:
- `OpenInputPropertiesDialog`
- `OpenInputFiltersDialog`
- `OpenInputInteractDialog`
Closes #846 
Users wanted to open the various dialogs for inputs, to use as hotkeys.
Tested OS(s): Ubuntu 20.04, ran all requests with no leaks
> RequestHandler: Add input open dialog requests

- src/eventhandler/EventHandler.cpp
- src/eventhandler/EventHandler.h
- src/eventhandler/EventHandler_Inputs.cpp
- src/requesthandler/RequestHandler.cpp
- src/requesthandler/RequestHandler.h
- src/requesthandler/RequestHandler_Inputs.cpp
Adds event `InputAudioBalanceChanged`
Adds requests:
- `GetInputAudioBalance`
- `SetInputAudioBalance`
Closes #858
More features!
> Input audio requests and events

- src/eventhandler/EventHandler_SceneItems.cpp
Adjust the field name to the one that is accepted by the request.
The docs were mentioning a field that doesn't exist, probably just a copy & paste mistake.
> docs: Fix wrong field name in `SceneItemLockStateChanged`

- src/requesthandler/types/RequestBatchExecutionType.h
- src/websocketserver/WebSocketServer_Protocol.cpp
Adjusts the int type of the `RequestBatchExecutionType` enum to `int8_t` and changes the type during JSON extraction.
Clang was warning about an invalid comparison as the execution type was extract as an `uint8_t`, whereas the enum used the `int` type (default, I believe?). Changing to an `int8_t` should be more than sufficient as the enum is extremely small and it's unlikely to grow over 127 different batch execution types in the future.
Plugin works as expected when run. Didn't test the batch execution in particular though.
-  [x] All commit messages are properly formatted and commits squashed …
> server: Fix int type of batch execution enum

- README.md
Add the library [obs-websocket-gd](https://github.com/you-win/obs-websocket-gd) to the library list. API changes for 5.0.0 have been completed.
Adds obs-websocket-gd to the library list.
Tested OS(s): Windows 10
A small demo/test project is included in the repo which can be run against a running obs-websocket instance. The project simply echos the response from obs-websocket.
> README: Add Godot obs-websocket-gd to library list

- README.md
- src/Config.cpp
- src/Config.h
- src/websocketserver/WebSocketServer.cpp
Socket listening default changed to IPv4 and IPv6,
overridable to IPv4 only by using the command line switch.
Switch websocketpp binding to both IPv4 & IPv6 by default. Add command line switch to force IPv4 only.
To enable IPv6.
Tested OS(s): 
Kubuntu 21.10.
OBS Studio: 27.2.2-0obsproject1~impish
Using "ss -plunt" example output, with command line switch to limit to IPv4:
tcp LISTEN 0 4096 0.0.0.0:4455 0.0.0.0:* users:(("obs",pid=6059,fd=14))
And without:
tcp LISTEN 0 4096 *:4455 : users:(("obs",pid=6059,fd=14))
-  [x ] I have read the [Contributing Guidelines](https://github.com/obsproject/obs-websocket/wiki/Contributing-Guidelines).
-  [x ] All commit messages are properly formatted and commits squashed where appropriate.
- …
> Server: Add --websocket_ipv4_only switch

- docs/README.md
- src/requesthandler/RequestHandler.cpp
- src/requesthandler/RequestHandler.h
- src/requesthandler/RequestHandler_Ui.cpp
Adds a new request `GetMonitorList` that returns a json Array of
objects containing data about connected monitors. See Issue #868
Adds `GetMonitorList` endpoint as requested in #868 
Adds the ability for clients to get monitor information. This can be useful for changing client behavior based on monitor resolution, position, presence of multiple monitors etc. 
- tested end to end from a python script using simpleobsws (V1.3.1)
Tested OS(s): Linux, Ubuntu 21.10
-  [ x ] I have read the [Contributing Guidelines](https://github.com/obsproject/obs-websocket/wiki/Contributing-Guidelines).
-  [ x ] All commit messages are properly formatted and commits squashed where appropriate.
-  [ x ] My code is not …
> Requests: Add GetMonitorList

- src/requesthandler/RequestHandler.cpp
- src/requesthandler/RequestHandler.h
- src/requesthandler/RequestHandler_Outputs.cpp
- src/requesthandler/RequestHandler_Stream.cpp
- src/requesthandler/RequestHandler_Ui.cpp
- src/requesthandler/rpc/Request.cpp
- src/requesthandler/rpc/Request.h
- src/utils/Obs.h
- src/utils/Obs_ArrayHelper.cpp
Adds the following requests as documented in the planned requests sheet:
- GetOutputList
- GetOutputStatus
- ToggleOutput
- StartOutput
- StopOutput
- GetOutputSettings
- SetOutputSettings
Combined with #929, this should be the last of the requests that need to be implemented for v5 to have feature parity with v4, thus making it ready for release.
Tested OS(s): 
All requests were tested with OBS 27.2.2 on macOS 11.6.1
-  [x] I have included updates to all appropriate …
> Requests: Add Outputs requests

- src/plugin-macros.h.in
Fixes the version string when built as submodule as part of `obs-studio`.
Currently the version string is always empty when building the latest master branch of `obs-studio` with obs-websocket included.
Tested OS(s): macOS
Rebuilt obs-studio and confirmed the version string is returned on the API.
> base: Fix version string when built as submodule

- README.md
I finally had the opportunity migrate the Go library to the v5 protocol, and would like to add it back to the list!
To spread the love!
Tested OS(s): Windows, Ubuntu via WSL, Alpine via Docker
Most of the code is generated from the `protocol.json`, and so are the functional tests!
> README: Add a Go client library to the list

- CMakeLists.txt
- Update compile options to allow the usage of Clang under Linux (and maybe even Windows).
- Remove some `-Wno-*` options that does not seem to be required anymore.
Cleanup and allow building with Clang on Linux.
Tested OS(s): 
- ArchLinux with Clang 14 and GCC 12
- https://github.com/obsproject/obs-studio/pull/6759 CI
> Update non-MSVC compile options

- src/requesthandler/RequestHandler_Record.cpp
I fixed this typo in ouputPaused, in the record status event.
This PR fixes the generated Doc and official client libs like obs-websocket-js.
Tested OS(s): Windows 11
> docs: Fix ouputPaused typo

- docs/generated/protocol.json
- docs/generated/protocol.md
- src/requesthandler/RequestHandler_General.cpp
Adds docstring for `CustomEvent`.
I wasn't sure where to add this (I'm new to the codebase and not fluent in C++). It looks like all other doc entries correspond 1:1 with a method, however I couldn't find any method that uses `CustomEvent` except for `RequestHandler::BroadcastCustomEvent` which already has a docstring.
So, I just put another docstring above that and it seems to generate the docs correctly.
Resolves #1031
Tested OS(s):  MacOS 12.6
I ran `build_docs.sh` to visually test the changed docs
-  [x] My code is not …
> Add CustomEvent docs entry

- src/eventhandler/EventHandler_Inputs.cpp
Small docs fix - this is not a multimap, it's a simple linear multiplier (the square root of the quadratic scale that would be shown to a user).
Clarify documentation
Looks fine visually. Docs-only change.
> Fix description of "mul" volume notation

- CMakeLists.txt
Disables timestamps in Qt resources to make builds reproducible.
Complete https://github.com/obsproject/obs-studio/pull/8220 (obs-websocket is the only component not reproducible right now)
Has not been tested directly yet, but the same change in OBS itself worked.
> base: Disable Qt RCC timestamps

- CMakeLists.txt
#1107 was meant to be done only on Windows, if not it might cause issues on Linux builds because of incompatible options.
Align with other plugins (with Qt) CMake and avoid issues on Linux builds.
Tested OS(s): 
> base: Disable Qt RCC timestamps only on Windows

- CMakeLists.txt
- cmake/legacy.cmake
- src/eventhandler/EventHandler.h
- src/forms/ConnectInfo.h
- src/forms/SettingsDialog.h
- src/requesthandler/RequestHandler.h
- src/utils/Crypto.cpp
- src/utils/Json.cpp
- src/utils/Obs.cpp
- src/utils/Obs_ActionHelper.cpp
- src/utils/Obs_ArrayHelper.cpp
- src/utils/Obs_NumberHelper.cpp
- src/utils/Obs_ObjectHelper.cpp
- src/utils/Obs_SearchHelper.cpp
- src/utils/Obs_StringHelper.cpp
- src/utils/Platform.cpp
- src/websocketserver/WebSocketServer.h
- src/websocketserver/rpc/WebSocketSession.h
Fix generated header inclusion that is actually broken on CMake 3.0 which break macOS build.
To fix it the right way, changes to CMake 2.0 and `#include`s should be done.
Fix macOS CIs
Tested OS(s): ArchLinux (CMake 2.0)
macOS CIs does build on my OBS Studio fork.
Run: https://github.com/tytan652/obs-studio/actions/runs/4531877056
> base: Fix generated header inclusion

- CMakeLists.txt
Asio and WebSocket++ are no longer added as submodules.
They are now included in obs-deps.
Surely an oversight while rebasing #1102 after #1097 got merged.
Purely cleanup
Tested OS(s): 
> base: Remove unneeded include directories

- CMakeLists.txt
Silences warnings triggered by Qt code design (relying on questionable comma usage and using quoted header imports in their Frameworks).
Required for https://github.com/obsproject/obs-studio/pull/8678
Tested on macOS 13 with Xcode default compiler settings.
> cmake: Silences Qt warnings emitted by clang with default Xcode settings

- .gitmodules
- CMakeLists.txt
- cmake/legacy.cmake
- src/forms/ConnectInfo.cpp
Requires to work on obs-studio repo:
- https://github.com/obsproject/obs-deps/pull/182
- https://github.com/obsproject/obs-studio/pull/8943
- **Drop Ubuntu 20.04**, related CI will failed because of an API break from Libqrcodegen between 1.5.0 (20.04) and 1.7.0 (22.04) (header file name change) with obs-websocket PRs.
Reduce to zero the number of submodule in obs-websocket repo.
Tested OS(s): Arch Linux
Test binaries available on a PR on my obs-studio fork: https://github.com/tytan652/obs-studio/pull/13
-  [x] My …
> base,deps,src: Replace qr submodule by prefix/system install

- data/locale/en-US.ini
Remove two obsolete translations `OBSWebSocket.Server.StartFailed.Title` and `OBSWebSocket.Server.StartFailed.Message`.
The text was originally introduced at the commit d76ff16162bcbbc07c9c2538624e515070c916f9.
The source code using the text was later removed.
Tested OS(s): Linux
Checked that a command below shows nothing.
```
git grep StartFailed ':(exclude)*.ini'
```
-  [x] I have included updates to all …
> locale: Remove obsolete translations

- .github/workflows/crowdin_upload.yml
Adds the obs-crowdin-sync GitHub Action to enable automatic upload of English language files to Crowdin.
`CROWDIN_SYNC_CROWDIN_PAT` was already added as an organization secret.
Automation is great.
In a fork.
> CI: Add obs-crowdin-sync

- src/obs-websocket.cpp
This PR removes `_config->Save()` from `obs_module_unload`.
Less number of error logs is better.
When `obs_module_unload` is called, the frontend API is no longer available so that `_config->Save()` is failing with error messages. Since the configuration is saved from the OK or the Apply button on the dialog, it is not necessary to save it again at `obs_module_unload`.
Tested OS(s): Fedora 37
Run obs and exit it. Checked the log message shows no line below.
```
Tried to call obs_frontend_get_global_config with no callbacks!
[obs-websocket] [Config::Save] Unable to fetch OBS config!
```
-  [x] All commit messages …
> base: Fix error to save configuration at obs_module_unload

- CMakeLists.txt
Changes identifiers for qrcodegen to use unified identifier provided by CMake packages.
qrcodegen is identified as such (without the "lib" prefix) and as the target "qrcodegencpp::qrcodegencpp" by the CMake package generated by obs-deps.
Requires https://github.com/obsproject/obs-deps/pull/214 to be merged and released.
Needs to be integrated into https://github.com/obsproject/obs-studio/pull/9601.
Tested by building OBS Studio with websocket support and all related changes applied.
Tested OS(s): Windows 11, macOS 13.5.2, Ubuntu 22.10
-  [x] All commit messages are properly formatted and commits squashed where …
> cmake: Update library and target names for qrcodegen

- CMakeLists.txt
The CMake generator expression to enable plugin tests mistakenly used a string literal, which evaluated to 1, which enabled the plugin tests. Use variable notation to correctly test this value.
Tested OS(s): 
* Windows 11
Tested configured builds locally and checked the resulting value of `PLUGIN_TESTS`.
> cmake: Fix condition to disable plugin tests

- CMakeLists.txt
Cleans up the CMake build script to go with the changes introduced by https://github.com/obsproject/obs-studio/pull/9769.
Reduce code complexity and makes CMake code easier to read in places.
Tested on Windows 11, macOS 14, and Ubuntu 23.04.
> cmake: Update formatting and switch to native find_package call for Qt6

- src/requesthandler/RequestHandler_General.cpp
- src/utils/Obs.h
- src/utils/Obs_SearchHelper.cpp
Add optional context to TriggerHotkeyByName
The same hotkey name can exist on multiple context, to make sure we got the correct one add an optional context
Tried calling 
`{
"requestType": "TriggerHotkeyByName",
"requestData": {
"hotkeyName": "OBSBasic.SelectScene",
"contextName": "Scene 1"
}
}`
Tested OS(s): Windows 11
- New request/event (non-breaking) 
> requesthandler: Add optional context to TriggerHotkeyByName

- src/utils/Platform.cpp
Check system tray is available before trying to use it. Fixes https://github.com/obsproject/obs-studio/issues/9991
Crash fix.
Hasn't.
> Utils: Check system tray exists before trying to use it

- src/requesthandler/RequestHandler_Config.cpp
Replaced `OBSService` type with `OBSServiceAutoRelease` in `RequestHandler::SetStreamServiceSettings`.
Memory leaks when setting streaming service using obs-websocket.
Tested OS(s): Ubuntu 22.04
Steps to test the memory-leak is as below.
1. Start obs with clean configuration
```
export XDG_CONFIG_HOME=$(mktemp -d /dev/shm/obs-XXXXXX)
obs &
```
1. In the wizard, configure `Optimize just for recording, I will not be streaming`.
2. Enable WebSocket server
1. also disable password for simple testing.
4. Run these lines in python3
```
import obsws_python
cl = obsws_python.ReqClient(host='localhost', port=4455)
cl.send('SetStreamServiceSettings', {
'streamServiceType': 'rtmp_custom',
'streamServiceSettings': {
'server': 'rtmp://localhost/live',
'key': 'secret',
}})
```
5. Exit obs
- Bug fix …
> RequestHandler: Fix memory leak when setting streaming service

- lib/obs-websocket-api.h
Fix compile errors and warnings in `lib/obs-websocket-api.h` so that the file can be included from both C and C++ code.
Using C++ on GCC, there was warnings below. We need to add remaining initializers.
```text
lib/obs-websocket-api.h:56:27: warning: missing initializer for member ‘calldata::size’ [-Wmissing-field-initializers]
56 |         calldata_t cd = {0};
|                           ^
```
Using C on Clang, 
```text
obs-websocket-api.h:47:1: error: 'inline' can only appear on functions inline proc_handler_t *_ph;
```
```text
obs-websocket-api.h:107:15: error: must use 'struct' tag to refer to type 'obs_websocket_request_response'
static inline obs_websocket_request_response *obs_websocket_call_request(const char *request_type, obs_data_t *request_data = NULL)
^
struct 
```
```text …
```
> lib: Fix compile errors on C and warnings on C++

- .github/workflows/crowdin_upload.yml
- .github/workflows/generate_docs.yml
- .github/workflows/lint.yml
CI: Update first-party GitHub Actions to v4
GitHub Actions has deprecated actions based on node16. The v4 actions are based on node20. Replace first-party v2/v3 actions with their v4 counterparts.
GitHub Actions has deprecated actions based on node12 and forces them to run on node16, which is also deprecated. Update to v4 actions to avoid warnings on CI.
See:
* https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
* https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
Want less CI warnings and don't want CI to stop working when node12/node16 are disabled.
This is on CI. obs-deps, obs-studio, obs-browser, and obs-plugintemplate have had successful runs with updated first-party actions. …
> CI: Update first-party GitHub Actions to v4

- CMakeLists.txt
- cmake/legacy.cmake
- cmake/obs-websocket-api.cmake
- cmake/obs-websocket-apiConfig.cmake.in
- src/WebSocketApi.h
Relies on:
- https://github.com/obsproject/obs-studio/pull/10100
This enables the installation of the header in the include directory by exporting it as an interface target
No more copy-pasting the header to use it
Tested OS(s): 
- Arch Linux
Windows and macOS headers needs to be checked
- Tested on Windows,  `--component Development` adds the header
> cmake,lib,base: Export obs-websocket-api as a target

- src/requesthandler/RequestHandler_SceneItems.cpp
- src/utils/Obs_ObjectHelper.cpp
Add `cropToBounds` to scene item
Was added in obs, but not in obs-websocket yet
The new `obs_sceneitem_set_info2` is used but `crop_to_bounds` is not set
On windows 11 by getting and setting
- New request/event (non-breaking) 
> requesthandler: Add `cropToBounds` to scene item

- src/requesthandler/RequestHandler_General.cpp
Fix releasing hotkeys triggered by name
Hotkey pairs require the other hotkey to be released before it can be pressed.
It is done for `TriggerHotkeyByKeySequence`, but not for `TriggerHotkeyByName`
by calling both hotkeys of an hotkey pair with `TriggerHotkeyByName`
Tested OS(s): 
Windows 11
- Bug fix (non-breaking change which fixes an issue) 
> requesthandler: Fix releasing hotkeys triggered by name

- src/Config.cpp
Use `u8path` to construct the `std::filesystem::path` to ensure the string is correctly treated as UTF-8.
Fixes crash on startup if OBS is installed on non-English systems.
Tested on a Windows VM with a user named `くそ`, while I could not reproduce the crash, I could reproduce the plugin not loading due to the migration failing. With this patch it worked and loaded up normally.
-  [x] I have included updates to all appropriate …
> Config: Ensure conversion to filesystem::path uses utf-8

- CMakeLists.txt
Downgrades the deprecated declarations error to warnings for GCC compilations in line with Clang and AppleClang.
Error has already been downgraded for Clang and AppleClang, not doing so for GCC was an oversight.
Tested OS(s): Ubuntu 24.04
> cmake: Downgrade deprecation error for GCC compilations

- CMakeLists.txt
Downgrades the error for use of deprecated declarations to a warning on Windows. Follow-up PR to #1241.
Error has already been downgraded for Clang, AppleClang, and GCC.
Tested OS(s): Windows 11
> cmake: Downgrade deprecation error for MSVC compilations

- src/forms/SettingsDialog.cpp
qt/qtbase@3512fb1ec5ff088772170540c4e91b1886fbea45 (also cherry-picked to https://github.com/qt/qtbase/commit/02ba4b14dc1c0cee802d8d840315833fda2449b4) deprecated the stateChanged signal of QCheckBoxes in favor of a new checkStateChanged signal. The signals are the same, except that now the enum type is passed explicitly (before the enum was passed as an argument but defined as an int).
The documentation states that it's deprecated for 6.9 but I got the warning now already (dev version appears to be 6.8 currently) and it's also picked to 6.7 and the alternative exists since 6.7 so I'm not 100% what the "real" deprecation version is but 6.7 makes sense.
Got a deprecation warning when compiling against Qt dev branch.
See:
* https://github.com/obsproject/obs-studio/pull/10732
Tested OS(s):
* …
> SettingsDialog: Fix Qt 6.7 checkbox signal deprecations

- src/requesthandler/RequestHandler_Config.cpp
Fixes #1264 
~~This just updates the function name invoked to the new one outlined in https://github.com/obsproject/obs-studio/commit/b9808eaca82340132c56e1577ae58a1e8747a119~~
~~Conceptually to prevent this fault in future should move to `obs_frontend_create_profile` instead?~~
Move create and delete profile to their API functions instead
WebSocket function for `CreateProfile` is not working in 31 beta due to internal function rename and not using an API function
Tested OS(s): 
-  [x] I …
> Fix profile functions that direct call a method instead of the API

- CMakeLists.txt
We know this is the minimum version that we require, so we can just fail during configure if somehow an older version is found.
See:
* https://github.com/obsproject/obs-browser/pull/452
* https://github.com/obsproject/obs-studio/pull/11384
Although we no longer support Ubuntu 22.04 for building or running OBS Studio, we can make the dependency requirement here more obvious at configure time.
Tested OS(s): 
* Windows 11
-  [x] My code is …
> cmake: Set minimum version for nlohmann_json to 3.11

- src/utils/Json.cpp
Use `u8path` when creating a file system path via a provided `std::string`.
All other path operations in the code base already use u8path to ensure that the strings provided by libobs (which will either be ASCII or UTF-8 byte sequences) are correctly converted into UTF-16 strings.
Fixes #1244.
Has not been tested locally, will need simple reproducer first.
> utils: Use u8path to fix possible string conversion crashes on Windows

- src/eventhandler/EventHandler_Scenes.cpp
When OBS Studio is started in Studio Mode, if a scene collection was not successfully found and loaded, the OBS Frontend API would, prior to https://github.com/obsproject/obs-studio/commit/577e3504d59f0d8e488ada7a05295d1d8267f095, emit OBS_FRONTEND_EVENT_SCENE_CHANGED and
OBS_FRONTEND_EVENT_PREVIEW_SCENE_CHANGED anyway. This would result in currentScene here being a nullptr, causing a crash.
For completeness, check for nullptr here so that we cannot crash if obs_frontend_get_current_scene() returns a nullptr.
https://github.com/obsproject/obs-studio/pull/11897
https://github.com/obsproject/obs-studio/commit/577e3504d59f0d8e488ada7a05295d1d8267f095
Tested OS(s): 
I haven't personally tested this, but this change was discussed while reviewing …
> eventhandler: Fix possible crash on OBS start in Studio Mode

- .clang-format
- src/requesthandler/RequestHandler_Inputs.cpp
This changes the formatting for the repository to clang-format 19.1.1, same as upstream obs-studio.
New changes to .clang-format from obs-studio are brought over (see obsproject/obs-studio@b3ab79291659dd40f6eeab016a62b742a9acff99), but the submodule-specific modifications are left in place (see 5fc39ef054db4a5976b903921fb8965c100ee31e).
Got formatting changes when doing `./build-aux/run-clang-format` on obs-studio, which is annoying.
Running `./build-aux/run-clang-format` on obs-studio no longer produces any changes. Still compiles.
This repo doesn't have any formatting check, so there is no CI to test.
-  [x] I have read the [Contributing Guidelines](https://github.com/obsproject/obs-websocket/wiki/Contributing …
> base: Apply latest clang-format changes from upstream
